__default__:
  account: mtcraig98
  partition: standard
  email: mchjones@umich.edu
  walltime: 02:00:00   # time limit for each job
  cpus_per_task: 8  # number of cores per job
  chdir: $GROUP_HOME/mchjones/pypsa-usa/workflow
  output: logs/{rule}/log-%j.out
  error: logs/{rule}/errlog-%j.err

build_renewable_profiles:
  walltime: 06:00:00

add_electricity:
  walltime: 06:00:00

simplify_network:
  walltime: 09:00:00

cluster_network:
  walltime: 09:00:00

solve_network:
  walltime: "120:00:00"

solve_network_validation:
  walltime: 09:00:00

add_demand:
  walltime: 02:00:00